backend:
  name: github
  repo: GUkirito/GUkirito.github.io
  branch: main

media_folder: static/images
public_folder: /images

collections:
  - name: post
    label: 文章
    folder: content/posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "日期", name: "date", widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false }
      - { label: "摘要", name: "description", widget: "string", required: false }
      - { label: "正文", name: "body", widget: "markdown" }